server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: XXX
    password: XXX
  # 文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: XXX
    accessKeyId: XXX
    accessKeySecret: XXX
    bucketName: XXX
    prefix: blog/

# JWT配置
jwt:
  secret: 12345678901234567890123456789012
  expiration: 86400000